# Generated by Django 3.1.4 on 2021-01-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_auto_20201231_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Add a snippet to display on blog index page', max_length=400),
        ),
    ]
